#!/bin/bash

#../src/runner/testcpp-runner ./libfoo \
#   -L../src/listeners -l"testcppxmllistener result.xml" -l"testcppstdoutlistener -c" \
#   -fTest*:testcase1 -f:testcase2 -f*:* -c9999 -s

../src/runner/testcpp-runner ./libfoo \
   -L../src/listeners -l"testcppxmllistener result.xml" -l"testcppstdoutlistener" \
   -fTest*:testcase1 -f:testcase2 -f*:* -c100 $@
