#!/bin/bash

../src/runner/testngpp-runner libmockcpp-ut-TestAny \
   -L../src/listeners \
   -l"testngppstdoutlistener -c -s -f -v" \
   -t"* > ^$" -c100 $@


#   -l"testngppxmllistener result.xml" 
