#!/bin/bash

../build/src/runner/testngpp-runner libsample \
   -L../build/src/listeners -l"testngppxmllistener result.xml" -l"testngppstdoutlistener -c" \
   -fTest*:testcase1 -f:testcase2 -f*:* -t"[ft slow empty] > [it fast]" -c100 $@
